# Generated by Django 4.2.7 on 2023-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('center', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('word', models.CharField(blank=True, max_length=50)),
                ('bed', models.CharField(blank=True, max_length=50)),
                ('regi_no', models.CharField(max_length=50, unique=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('admited', 'Admited'), ('released', 'Released')], default='admited', max_length=10)),
                ('father_or_husband', models.CharField(blank=True, max_length=50)),
                ('mother', models.CharField(blank=True, max_length=50)),
                ('mailing_address', models.CharField(blank=True, max_length=250)),
                ('permanent_address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=50)),
                ('contact_person_phone', models.CharField(blank=True, max_length=15)),
                ('con_doctor', models.CharField(max_length=50)),
                ('con_doctor_depart', models.CharField(blank=True, max_length=50)),
                ('con_doctor_unit', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
