# Generated by Django 4.2.7 on 2023-11-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=50, verbose_name='Patient Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Patient Bed'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='center',
            field=models.CharField(blank=True, max_length=50, verbose_name='Center for Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='con_doctor',
            field=models.CharField(max_length=50, verbose_name='Consaltant Doctor Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='con_doctor_depart',
            field=models.CharField(blank=True, max_length=50, verbose_name='Consaltant Doctor Department'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='con_doctor_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Consaltant Doctor Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contact Person Name of Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Person Phone Number of Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='Enter Patiend Department Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_or_husband',
            field=models.CharField(blank=True, max_length=50, verbose_name='Patient Father or Husband Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='Patient Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Patient Present Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mother',
            field=models.CharField(blank=True, max_length=50, verbose_name='Patient Mother Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Enter Patiend ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Patient Permanent Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Patient Phone Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='regi_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Patiend Registration Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='word',
            field=models.CharField(blank=True, max_length=50, verbose_name='Patient Word'),
        ),
    ]
