# Generated by Django 4.2.7 on 2023-11-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_patient_age_alter_patient_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
